export const argTypes = {
  gap: {
    control: "select",
    options: [
      "size000",
      "size00",
      "size1",
      "size2",
      "size3",
      "size4",
      "size5",
      "size6",
      "size7",
      "size8",
      "size9",
      "size10",
      "size11",
      "size12",
      "size13",
      "size14",
      "size15",
    ],
    description: "Sets space between each element using spacing constants",
  },
  minItemWidth: {
    control: "text",
    description:
      "Sets minimum width for each column (CSSLength, number, or size constant)",
  },
  variant: {
    control: "select",
    options: ["default", "centered"],
    description: "Sets columns to centered layout when variant='centered'",
  },
  padding: {
    control: "select",
    options: [
      undefined,
      "size000",
      "size00",
      "size1",
      "size2",
      "size3",
      "size4",
      "size5",
      "size6",
      "size7",
      "size8",
      "size9",
      "size10",
      "size11",
      "size12",
      "size13",
      "size14",
      "size15",
    ],
    description:
      "Sets padding on the component using design system spacing scale",
  },
  as: {
    control: "none",
  },
};
