export const argTypes = {
  gap: {
    control: "select",
    options: [
      "size000",
      "size00",
      "size1",
      "size2",
      "size3",
      "size4",
      "size5",
      "size6",
      "size7",
      "size8",
      "size9",
      "size10",
      "size11",
      "size12",
      "size13",
      "size14",
      "size15",
    ],
    description: "Sets space between each element using spacing constants",
  },
  justify: {
    control: "select",
    options: ["start", "end", "center", "space-between", "space-around"],
    description: "Specifies the inline alignment of the children",
  },
  align: {
    control: "select",
    options: ["start", "end", "center", "stretch"],
    description: "Specifies the block alignment of the children",
  },
};
